{
 "title": "Otus Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "метрики сервиса", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS с разбивкой по API методам",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (route) (rate(http_requests_total{service=\"lotus\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate - количество 500ых ответов",
   "type": "timeseries",
   "description": "с разбивкой по API методам",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum by (route, status_code) (rate(http_requests_total{service=\"lotus\",status_code=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{service=\"lotus\"}[1m])))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{service=\"lotus\"}[1m])))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{service=\"lotus\"}[1m])))",
     "legendFormat": "99%"
    },
    {
     "expr": "max (rate(http_request_duration_seconds_bucket{service=\"lotus\"}[1m]))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Response time 95 %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route) (rate(http_request_duration_seconds_bucket{service=\"lotus\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}